const translations = {
  en: {
    pageTitle: "Hue9 Accessibility — Sudoku beyond color",
    pageDescription: "Discover the accessibility features in Hue9: Color Sudoku, including Symbol Mode, VoiceOver, Larger Text, Increased Contrast, Dark Mode and Reduce Motion.",
    skip: "Skip to content",
    navLabel: "Main navigation",
    languageLabel: "Language",
    legalLabel: "Legal links",
    supportedLabel: "Supported accessibility features",
    navFeatures: "Features",
    navEnable: "How to enable",
    navContact: "Contact",
    heroEyebrow: "Accessibility in Hue9",
    heroTitle: "Sudoku beyond color.",
    heroIntro: "Hue9 is designed so color is never the only way to play. Symbols, spoken context, scalable text and calmer motion keep every puzzle readable, understandable and yours.",
    explore: "Explore the features",
    appStore: "View on the App Store",
    pillVoiceOver: "VoiceOver",
    pillSymbols: "Symbol Mode",
    pillText: "Larger Text",
    pillMotion: "Reduce Motion",
    pillContrast: "Increased Contrast",
    heroCaptionSmall: "Nine colors.",
    heroCaptionLarge: "Nine unmistakable symbols.",
    principleEyebrow: "Designed with a second language",
    principleTitle: "Color creates the puzzle.<br>It never has to carry it alone.",
    principleBody: "Accessibility is part of Hue9’s game design, not a layer added afterwards. Every state that color communicates has another cue: shape, position, contrast, text or speech.",
    featuresEyebrow: "Made for different ways of playing",
    featuresTitle: "A board that meets you where you are.",
    symbolsKicker: "Differentiate Without Color",
    symbolsTitle: "Every color has a second language.",
    symbolsBody: "Symbol Mode pairs each of Hue9’s nine colors with a unique shape. The board, color selector, pencil notes and visual feedback remain understandable without relying on hue alone — while the original colors stay visible.",
    symbolsSystem: "Hue9 also responds automatically to the iOS “Differentiate Without Color” setting.",
    symbolScreenshotAlt: "A real Hue9 game board using nine colors paired with nine distinct symbols.",
    symbolScreenshotLabel: "Actual in-game board",
    symbolScreenshotMode: "Symbol Mode · iPhone",
    voiceKicker: "VoiceOver",
    voiceTitle: "The whole board, in words.",
    voiceBody: "Every cell identifies its row and column, then announces its value, pencil notes and current state. Controls have meaningful labels, and important game results are spoken when they happen.",
    voiceSampleLabel: "Row 4, column 7",
    voiceSampleValue: "Blue triangle, selected",
    textKicker: "Larger Text",
    textTitle: "Built to flex, not clip.",
    textBody: "Hue9 supports Dynamic Type throughout the app. Navigation, settings, onboarding and game information adapt as text size increases, with layouts that reflow when space is limited.",
    motionKicker: "Reduce Motion",
    motionTitle: "Less motion. Same meaning.",
    motionBody: "With Reduce Motion enabled, entrance movement, pulsing cues, shakes and celebration effects are removed or replaced with brief fades. Feedback remains clear without demanding movement.",
    contrastKicker: "Contrast & appearance",
    contrastTitle: "Comfortable in every light.",
    contrastBody: "Light, Dark and System appearances work across common tasks. Increased Contrast strengthens key boundaries and controls, while carefully chosen themes keep the board legible.",
    zenKicker: "Zen Mode",
    zenTitle: "A quieter place to think.",
    zenBody: "Zen Mode removes the timer, level, hints and other competitive signals from the game screen. It leaves the puzzle and its essential controls, reducing visual pressure without changing the logic.",
    enableEyebrow: "Make Hue9 yours",
    enableTitle: "Turn features on in a few taps.",
    enableIntro: "Hue9 follows your iOS accessibility settings automatically. Symbol Mode and Zen Mode can also be selected directly inside the app.",
    stepSymbolTitle: "Symbol Mode in Hue9",
    stepSymbolBody: "Open Hue9 → Settings → Accessibility → Symbol Mode. You can also change it from the settings button during a game.",
    stepSystemTitle: "iOS accessibility settings",
    stepSystemBody: "Open iOS Settings → Accessibility to configure VoiceOver, Display & Text Size, Motion and Differentiate Without Color.",
    stepZenTitle: "Zen Mode",
    stepZenBody: "Open Hue9 → Settings → Play Style → Zen Mode. Choose any difficulty and play without timers, levels or hints on screen.",
    commitmentEyebrow: "An ongoing practice",
    commitmentTitle: "Accessibility is never “finished.”",
    commitmentBody: "Hue9 is tested on iPhone and iPad with Apple’s accessibility settings, including hands-on VoiceOver navigation. Real-world feedback matters even more. If something is difficult to perceive, understand or operate, please tell me.",
    commitmentNote: "Accessibility support can vary by device, iOS version, language and text size.",
    contactEyebrow: "Help shape what comes next",
    contactTitle: "Found an accessibility barrier?",
    contactBody: "Tell me what happened, which device and iOS version you use, and which accessibility settings were active. Every report helps make Hue9 better.",
    contactButton: "Send accessibility feedback",
    footerTagline: "Pure logic, expressed your way.",
    privacy: "Privacy",
    terms: "Terms",
    support: "Support"
  },
  es: {
    pageTitle: "Accesibilidad en Hue9 — Sudoku más allá del color",
    pageDescription: "Descubre las funciones de accesibilidad de Hue9: Color Sudoku, como Modo símbolos, VoiceOver, Texto más grande, Contraste aumentado, Modo oscuro y Reducir movimiento.",
    skip: "Saltar al contenido",
    navLabel: "Navegación principal",
    languageLabel: "Idioma",
    legalLabel: "Enlaces legales",
    supportedLabel: "Funciones de accesibilidad compatibles",
    navFeatures: "Funciones",
    navEnable: "Cómo activarlas",
    navContact: "Contacto",
    heroEyebrow: "Accesibilidad en Hue9",
    heroTitle: "Sudoku más allá del color.",
    heroIntro: "Hue9 está diseñado para que el color nunca sea la única forma de jugar. Los símbolos, el contexto hablado, el texto adaptable y un movimiento más calmado hacen que cada puzzle sea legible, comprensible y tuyo.",
    explore: "Explorar las funciones",
    appStore: "Ver en el App Store",
    pillVoiceOver: "VoiceOver",
    pillSymbols: "Modo símbolos",
    pillText: "Texto más grande",
    pillMotion: "Reducir movimiento",
    pillContrast: "Contraste aumentado",
    heroCaptionSmall: "Nueve colores.",
    heroCaptionLarge: "Nueve símbolos inconfundibles.",
    principleEyebrow: "Diseñado con un segundo lenguaje",
    principleTitle: "El color crea el puzzle.<br>Nunca tiene que explicarlo todo solo.",
    principleBody: "La accesibilidad forma parte del diseño de Hue9; no es una capa añadida después. Cada estado que comunica el color cuenta con otra señal: forma, posición, contraste, texto o voz.",
    featuresEyebrow: "Hecho para distintas formas de jugar",
    featuresTitle: "Un tablero que se adapta a ti.",
    symbolsKicker: "Diferenciar sin color",
    symbolsTitle: "Cada color tiene un segundo lenguaje.",
    symbolsBody: "El Modo símbolos asocia cada uno de los nueve colores de Hue9 con una forma única. El tablero, el selector de color, las notas y las señales visuales siguen siendo comprensibles sin depender solo del tono, y los colores originales se mantienen.",
    symbolsSystem: "Hue9 también responde automáticamente al ajuste «Diferenciar sin color» de iOS.",
    symbolScreenshotAlt: "Un tablero real de Hue9 con nueve colores asociados a nueve símbolos diferentes.",
    symbolScreenshotLabel: "Tablero real de una partida",
    symbolScreenshotMode: "Modo símbolos · iPhone",
    voiceKicker: "VoiceOver",
    voiceTitle: "Todo el tablero, en palabras.",
    voiceBody: "Cada casilla identifica su fila y columna, y después anuncia su valor, notas y estado actual. Los controles tienen etiquetas claras y los resultados importantes se leen cuando ocurren.",
    voiceSampleLabel: "Fila 4, columna 7",
    voiceSampleValue: "Triángulo azul, seleccionado",
    textKicker: "Texto más grande",
    textTitle: "Crece sin recortarse.",
    textBody: "Hue9 admite Dynamic Type en toda la app. La navegación, los ajustes, la introducción y la información de la partida se adaptan cuando aumenta el tamaño del texto, reorganizando el contenido si falta espacio.",
    motionKicker: "Reducir movimiento",
    motionTitle: "Menos movimiento. El mismo significado.",
    motionBody: "Al activar Reducir movimiento, las entradas animadas, pulsos, sacudidas y celebraciones desaparecen o se sustituyen por fundidos breves. La respuesta sigue siendo clara sin exigir movimiento.",
    contrastKicker: "Contraste y apariencia",
    contrastTitle: "Cómodo con cualquier luz.",
    contrastBody: "Las apariencias Clara, Oscura y Sistema funcionan en las tareas habituales. Contraste aumentado refuerza límites y controles importantes, y los temas están elegidos para mantener el tablero legible.",
    zenKicker: "Modo Zen",
    zenTitle: "Un lugar más tranquilo para pensar.",
    zenBody: "El Modo Zen elimina de la partida el temporizador, el nivel, las pistas y otras señales competitivas. Deja el puzzle y sus controles esenciales para reducir la presión visual sin cambiar la lógica.",
    enableEyebrow: "Haz Hue9 tuyo",
    enableTitle: "Activa las funciones en pocos toques.",
    enableIntro: "Hue9 sigue automáticamente tus ajustes de accesibilidad de iOS. El Modo símbolos y el Modo Zen también pueden elegirse directamente dentro de la app.",
    stepSymbolTitle: "Modo símbolos en Hue9",
    stepSymbolBody: "Abre Hue9 → Ajustes → Accesibilidad → Modo símbolos. También puedes cambiarlo desde el botón de ajustes durante una partida.",
    stepSystemTitle: "Ajustes de accesibilidad de iOS",
    stepSystemBody: "Abre Ajustes de iOS → Accesibilidad para configurar VoiceOver, Pantalla y tamaño del texto, Movimiento y Diferenciar sin color.",
    stepZenTitle: "Modo Zen",
    stepZenBody: "Abre Hue9 → Ajustes → Estilo de juego → Modo Zen. Elige cualquier dificultad y juega sin temporizador, niveles ni pistas en pantalla.",
    commitmentEyebrow: "Una práctica continua",
    commitmentTitle: "La accesibilidad nunca está «terminada».",
    commitmentBody: "Hue9 se prueba en iPhone y iPad con los ajustes de accesibilidad de Apple, incluida la navegación manual con VoiceOver. La experiencia real importa todavía más. Si algo resulta difícil de percibir, entender o manejar, cuéntamelo.",
    commitmentNote: "La compatibilidad puede variar según el dispositivo, la versión de iOS, el idioma y el tamaño del texto.",
    contactEyebrow: "Ayuda a decidir qué viene después",
    contactTitle: "¿Has encontrado una barrera de accesibilidad?",
    contactBody: "Cuéntame qué ocurrió, qué dispositivo y versión de iOS utilizas y qué ajustes de accesibilidad estaban activos. Cada informe ayuda a mejorar Hue9.",
    contactButton: "Enviar comentarios de accesibilidad",
    footerTagline: "Lógica pura, expresada a tu manera.",
    privacy: "Privacidad",
    terms: "Términos",
    support: "Soporte"
  },
  de: {
    pageTitle: "Barrierefreiheit in Hue9 — Sudoku jenseits von Farbe",
    pageDescription: "Entdecke die Bedienungshilfen in Hue9: Color Sudoku, darunter Symbolmodus, VoiceOver, größerer Text, erhöhter Kontrast, Dunkelmodus und Bewegung reduzieren.",
    skip: "Zum Inhalt springen",
    navLabel: "Hauptnavigation",
    languageLabel: "Sprache",
    legalLabel: "Rechtliche Links",
    supportedLabel: "Unterstützte Bedienungshilfen",
    navFeatures: "Funktionen",
    navEnable: "Aktivierung",
    navContact: "Kontakt",
    heroEyebrow: "Barrierefreiheit in Hue9",
    heroTitle: "Sudoku jenseits von Farbe.",
    heroIntro: "Hue9 ist so gestaltet, dass Farbe nie die einzige Spielmöglichkeit ist. Symbole, gesprochener Kontext, skalierbarer Text und ruhigere Bewegungen machen jedes Rätsel lesbar, verständlich und zu deinem eigenen.",
    explore: "Funktionen entdecken",
    appStore: "Im App Store ansehen",
    pillVoiceOver: "VoiceOver",
    pillSymbols: "Symbolmodus",
    pillText: "Größerer Text",
    pillMotion: "Bewegung reduzieren",
    pillContrast: "Kontrast erhöhen",
    heroCaptionSmall: "Neun Farben.",
    heroCaptionLarge: "Neun unverwechselbare Symbole.",
    principleEyebrow: "Mit einer zweiten Sprache gestaltet",
    principleTitle: "Farbe erschafft das Rätsel.<br>Sie muss es nie allein tragen.",
    principleBody: "Barrierefreiheit ist Teil des Spieldesigns von Hue9 und keine nachträglich hinzugefügte Ebene. Jeder Zustand, den Farbe vermittelt, besitzt einen weiteren Hinweis: Form, Position, Kontrast, Text oder Sprache.",
    featuresEyebrow: "Für unterschiedliche Spielweisen",
    featuresTitle: "Ein Spielfeld, das sich dir anpasst.",
    symbolsKicker: "Ohne Farben differenzieren",
    symbolsTitle: "Jede Farbe hat eine zweite Sprache.",
    symbolsBody: "Im Symbolmodus wird jede der neun Farben von Hue9 mit einer einzigartigen Form kombiniert. Spielfeld, Farbauswahl, Notizen und visuelles Feedback bleiben verständlich, ohne allein vom Farbton abzuhängen — die ursprünglichen Farben bleiben sichtbar.",
    symbolsSystem: "Hue9 reagiert außerdem automatisch auf die iOS-Einstellung „Ohne Farbe unterscheiden“.",
    symbolScreenshotAlt: "Ein echtes Hue9-Spielfeld mit neun Farben, die neun unterschiedlichen Symbolen zugeordnet sind.",
    symbolScreenshotLabel: "Echtes Spielfeld aus einer Partie",
    symbolScreenshotMode: "Symbolmodus · iPhone",
    voiceKicker: "VoiceOver",
    voiceTitle: "Das ganze Spielfeld in Worten.",
    voiceBody: "Jede Zelle nennt ihre Zeile und Spalte und liest anschließend Wert, Notizen und aktuellen Zustand vor. Steuerelemente besitzen aussagekräftige Beschriftungen, wichtige Spielergebnisse werden beim Auftreten angesagt.",
    voiceSampleLabel: "Zeile 4, Spalte 7",
    voiceSampleValue: "Blaues Dreieck, ausgewählt",
    textKicker: "Größerer Text",
    textTitle: "Passt sich an, statt abzuschneiden.",
    textBody: "Hue9 unterstützt Dynamic Type in der gesamten App. Navigation, Einstellungen, Einführung und Spielinformationen passen sich an größere Schrift an; bei wenig Platz ordnen sich die Layouts neu.",
    motionKicker: "Bewegung reduzieren",
    motionTitle: "Weniger Bewegung. Gleiche Bedeutung.",
    motionBody: "Ist „Bewegung reduzieren“ aktiviert, werden Einblendbewegungen, pulsierende Hinweise, Erschütterungen und Feier-Effekte entfernt oder durch kurze Überblendungen ersetzt. Das Feedback bleibt klar, ohne Bewegung zu verlangen.",
    contrastKicker: "Kontrast & Darstellung",
    contrastTitle: "Angenehm bei jedem Licht.",
    contrastBody: "Die Darstellungen Hell, Dunkel und System funktionieren bei allen üblichen Aufgaben. „Kontrast erhöhen“ verstärkt wichtige Begrenzungen und Steuerelemente; sorgfältig gewählte Designs halten das Spielfeld gut lesbar.",
    zenKicker: "Zen-Modus",
    zenTitle: "Ein ruhigerer Ort zum Denken.",
    zenBody: "Der Zen-Modus entfernt Zeit, Level, Hinweise und weitere Wettbewerbssignale vom Spielbildschirm. Übrig bleiben das Rätsel und seine wesentlichen Steuerelemente — weniger visueller Druck bei unveränderter Logik.",
    enableEyebrow: "Mach Hue9 zu deinem Spiel",
    enableTitle: "Funktionen mit wenigen Fingertipps aktivieren.",
    enableIntro: "Hue9 übernimmt deine iOS-Bedienungshilfen automatisch. Symbolmodus und Zen-Modus lassen sich zusätzlich direkt in der App auswählen.",
    stepSymbolTitle: "Symbolmodus in Hue9",
    stepSymbolBody: "Öffne Hue9 → Einstellungen → Bedienungshilfen → Symbolmodus. Du kannst ihn auch während einer Partie über die Einstellungen ändern.",
    stepSystemTitle: "iOS-Bedienungshilfen",
    stepSystemBody: "Öffne iOS-Einstellungen → Bedienungshilfen, um VoiceOver, Anzeige & Textgröße, Bewegung und „Ohne Farbe unterscheiden“ einzustellen.",
    stepZenTitle: "Zen-Modus",
    stepZenBody: "Öffne Hue9 → Einstellungen → Spielstil → Zen-Modus. Wähle einen beliebigen Schwierigkeitsgrad und spiele ohne Zeit, Level oder Hinweise auf dem Bildschirm.",
    commitmentEyebrow: "Eine fortlaufende Aufgabe",
    commitmentTitle: "Barrierefreiheit ist nie „fertig“.",
    commitmentBody: "Hue9 wird auf iPhone und iPad mit Apples Bedienungshilfen getestet, einschließlich praktischer Navigation mit VoiceOver. Erfahrungen aus dem Alltag sind noch wichtiger. Wenn etwas schwer wahrzunehmen, zu verstehen oder zu bedienen ist, sag mir bitte Bescheid.",
    commitmentNote: "Die Unterstützung kann je nach Gerät, iOS-Version, Sprache und Textgröße variieren.",
    contactEyebrow: "Hilf mit, die nächsten Schritte zu gestalten",
    contactTitle: "Eine Barriere entdeckt?",
    contactBody: "Beschreibe, was passiert ist, welches Gerät und welche iOS-Version du verwendest und welche Bedienungshilfen aktiv waren. Jede Rückmeldung hilft, Hue9 zu verbessern.",
    contactButton: "Feedback zur Barrierefreiheit senden",
    footerTagline: "Pure Logik, auf deine Art ausgedrückt.",
    privacy: "Datenschutz",
    terms: "Bedingungen",
    support: "Support"
  },
  fr: {
    pageTitle: "Accessibilité de Hue9 — Le sudoku au-delà des couleurs",
    pageDescription: "Découvrez les fonctions d’accessibilité de Hue9: Color Sudoku, dont le mode Symboles, VoiceOver, le texte agrandi, le contraste renforcé, le mode sombre et Réduire les animations.",
    skip: "Aller au contenu",
    navLabel: "Navigation principale",
    languageLabel: "Langue",
    legalLabel: "Liens juridiques",
    supportedLabel: "Fonctions d’accessibilité prises en charge",
    navFeatures: "Fonctions",
    navEnable: "Activation",
    navContact: "Contact",
    heroEyebrow: "L’accessibilité dans Hue9",
    heroTitle: "Le sudoku au-delà des couleurs.",
    heroIntro: "Hue9 est conçu pour que la couleur ne soit jamais la seule manière de jouer. Symboles, contexte vocal, texte adaptable et animations apaisées rendent chaque grille lisible, compréhensible et vraiment personnelle.",
    explore: "Découvrir les fonctions",
    appStore: "Voir dans l’App Store",
    pillVoiceOver: "VoiceOver",
    pillSymbols: "Mode Symboles",
    pillText: "Texte agrandi",
    pillMotion: "Réduire les animations",
    pillContrast: "Augmenter le contraste",
    heroCaptionSmall: "Neuf couleurs.",
    heroCaptionLarge: "Neuf symboles impossibles à confondre.",
    principleEyebrow: "Conçu avec un second langage",
    principleTitle: "La couleur crée la grille.<br>Elle n’a jamais à tout porter seule.",
    principleBody: "L’accessibilité fait partie du game design de Hue9, ce n’est pas une couche ajoutée après coup. Chaque état communiqué par la couleur possède un autre repère : forme, position, contraste, texte ou parole.",
    featuresEyebrow: "Pour différentes façons de jouer",
    featuresTitle: "Une grille qui s’adapte à vous.",
    symbolsKicker: "Différencier sans couleur",
    symbolsTitle: "Chaque couleur possède un second langage.",
    symbolsBody: "Le mode Symboles associe chacune des neuf couleurs de Hue9 à une forme unique. La grille, le sélecteur, les notes et les retours visuels restent compréhensibles sans dépendre uniquement de la teinte, tandis que les couleurs d’origine restent visibles.",
    symbolsSystem: "Hue9 réagit aussi automatiquement au réglage iOS « Différencier sans couleur ».",
    symbolScreenshotAlt: "Une véritable grille Hue9 utilisant neuf couleurs associées à neuf symboles distincts.",
    symbolScreenshotLabel: "Véritable grille en cours de partie",
    symbolScreenshotMode: "Mode Symboles · iPhone",
    voiceKicker: "VoiceOver",
    voiceTitle: "Toute la grille, avec des mots.",
    voiceBody: "Chaque case indique sa ligne et sa colonne, puis annonce sa valeur, ses notes et son état actuel. Les commandes ont des libellés explicites et les résultats importants sont lus au moment où ils surviennent.",
    voiceSampleLabel: "Ligne 4, colonne 7",
    voiceSampleValue: "Triangle bleu, sélectionné",
    textKicker: "Texte agrandi",
    textTitle: "Conçu pour s’adapter, pas pour couper.",
    textBody: "Hue9 prend en charge Dynamic Type dans toute l’app. La navigation, les réglages, l’introduction et les informations de jeu s’adaptent lorsque le texte grandit, avec des mises en page qui se réorganisent si l’espace manque.",
    motionKicker: "Réduire les animations",
    motionTitle: "Moins de mouvement. Le même sens.",
    motionBody: "Lorsque Réduire les animations est activé, les mouvements d’entrée, pulsations, secousses et célébrations sont supprimés ou remplacés par de brefs fondus. Le retour reste clair sans imposer de mouvement.",
    contrastKicker: "Contraste et apparence",
    contrastTitle: "Confortable sous toutes les lumières.",
    contrastBody: "Les apparences Claire, Sombre et Système fonctionnent dans les tâches courantes. Augmenter le contraste renforce les limites et commandes essentielles, tandis que des thèmes soigneusement choisis préservent la lisibilité de la grille.",
    zenKicker: "Mode Zen",
    zenTitle: "Un espace plus calme pour réfléchir.",
    zenBody: "Le mode Zen retire de l’écran le chronomètre, le niveau, les indices et les autres signaux compétitifs. Il ne garde que la grille et ses commandes essentielles, réduisant la pression visuelle sans modifier la logique.",
    enableEyebrow: "Faites de Hue9 votre jeu",
    enableTitle: "Activez les fonctions en quelques gestes.",
    enableIntro: "Hue9 suit automatiquement vos réglages d’accessibilité iOS. Le mode Symboles et le mode Zen peuvent aussi être sélectionnés directement dans l’app.",
    stepSymbolTitle: "Mode Symboles dans Hue9",
    stepSymbolBody: "Ouvrez Hue9 → Réglages → Accessibilité → Mode Symboles. Vous pouvez également le modifier depuis le bouton des réglages pendant une partie.",
    stepSystemTitle: "Réglages d’accessibilité iOS",
    stepSystemBody: "Ouvrez Réglages iOS → Accessibilité pour configurer VoiceOver, Affichage et taille du texte, Mouvement et Différencier sans couleur.",
    stepZenTitle: "Mode Zen",
    stepZenBody: "Ouvrez Hue9 → Réglages → Style de jeu → Mode Zen. Choisissez n’importe quelle difficulté et jouez sans chronomètre, niveau ni indice à l’écran.",
    commitmentEyebrow: "Une démarche continue",
    commitmentTitle: "L’accessibilité n’est jamais « terminée ».",
    commitmentBody: "Hue9 est testé sur iPhone et iPad avec les réglages d’accessibilité Apple, notamment par une navigation réelle avec VoiceOver. Les retours du quotidien comptent encore davantage. Si quelque chose est difficile à percevoir, comprendre ou utiliser, dites-le-moi.",
    commitmentNote: "La prise en charge peut varier selon l’appareil, la version d’iOS, la langue et la taille du texte.",
    contactEyebrow: "Aidez à façonner la suite",
    contactTitle: "Vous avez rencontré un obstacle d’accessibilité ?",
    contactBody: "Indiquez-moi ce qui s’est passé, votre appareil, votre version d’iOS et les réglages d’accessibilité actifs. Chaque signalement contribue à améliorer Hue9.",
    contactButton: "Envoyer un retour d’accessibilité",
    footerTagline: "La logique pure, exprimée à votre façon.",
    privacy: "Confidentialité",
    terms: "Conditions",
    support: "Assistance"
  },
  ja: {
    pageTitle: "Hue9のアクセシビリティ — 色を超えた数独",
    pageDescription: "シンボルモード、VoiceOver、さらに大きな文字、コントラストを上げる、ダークモード、視差効果を減らすなど、Hue9: Color Sudokuのアクセシビリティ機能をご紹介します。",
    skip: "コンテンツに移動",
    navLabel: "メインナビゲーション",
    languageLabel: "言語",
    legalLabel: "法的情報へのリンク",
    supportedLabel: "対応しているアクセシビリティ機能",
    navFeatures: "機能",
    navEnable: "有効にする方法",
    navContact: "お問い合わせ",
    heroEyebrow: "Hue9のアクセシビリティ",
    heroTitle: "色を超えた数独。",
    heroIntro: "Hue9は、色だけに頼らず遊べるよう設計されています。シンボル、音声による状況説明、拡大できる文字、穏やかな動きによって、すべてのパズルを読みやすく、理解しやすく、自分らしく楽しめます。",
    explore: "機能を見る",
    appStore: "App Storeで見る",
    pillVoiceOver: "VoiceOver",
    pillSymbols: "シンボルモード",
    pillText: "さらに大きな文字",
    pillMotion: "視差効果を減らす",
    pillContrast: "コントラストを上げる",
    heroCaptionSmall: "9つの色。",
    heroCaptionLarge: "見分けやすい9つのシンボル。",
    principleEyebrow: "もう一つの言語とともに設計",
    principleTitle: "色がパズルを生み出す。<br>でも、色だけに任せる必要はありません。",
    principleBody: "アクセシビリティは後から追加した機能ではなく、Hue9のゲームデザインそのものです。色が伝えるすべての状態には、形、位置、コントラスト、文字、音声という別の手がかりがあります。",
    featuresEyebrow: "さまざまな遊び方のために",
    featuresTitle: "あなたに合わせてくれる盤面。",
    symbolsKicker: "カラー以外で区別",
    symbolsTitle: "すべての色に、もう一つの言語。",
    symbolsBody: "シンボルモードでは、Hue9の9色それぞれに固有の形を組み合わせます。元の色を表示したまま、盤面、カラー選択、メモ、視覚的なフィードバックを色合いだけに頼らず理解できます。",
    symbolsSystem: "Hue9はiOSの「カラー以外で区別」設定にも自動的に対応します。",
    symbolScreenshotAlt: "9つの色と9つの異なるシンボルを組み合わせた、実際のHue9のゲーム盤面。",
    symbolScreenshotLabel: "実際のゲーム盤面",
    symbolScreenshotMode: "シンボルモード · iPhone",
    voiceKicker: "VoiceOver",
    voiceTitle: "盤面全体を、言葉で。",
    voiceBody: "各マスは行と列を示し、値、メモ、現在の状態を読み上げます。操作には分かりやすいラベルが付き、重要なゲーム結果は発生したときに音声で伝えられます。",
    voiceSampleLabel: "4行目、7列目",
    voiceSampleValue: "青い三角、選択中",
    textKicker: "さらに大きな文字",
    textTitle: "切れずに、しなやかに広がる。",
    textBody: "Hue9はアプリ全体でDynamic Typeに対応しています。文字サイズを大きくすると、ナビゲーション、設定、オンボーディング、ゲーム情報が適応し、スペースが少ない場合はレイアウトが組み替わります。",
    motionKicker: "視差効果を減らす",
    motionTitle: "動きは少なく。意味はそのまま。",
    motionBody: "「視差効果を減らす」を有効にすると、登場時の動き、点滅する合図、揺れ、クリア演出がなくなるか、短いフェードに置き換わります。動きに頼らず、フィードバックは明確に保たれます。",
    contrastKicker: "コントラストと外観",
    contrastTitle: "どんな明るさでも快適に。",
    contrastBody: "ライト、ダーク、システムの外観は、一般的な操作全体で機能します。「コントラストを上げる」は重要な境界線や操作を強調し、厳選したテーマが盤面の読みやすさを保ちます。",
    zenKicker: "Zenモード",
    zenTitle: "考えるための、静かな場所。",
    zenBody: "Zenモードでは、タイマー、レベル、ヒントなど競争を意識させる表示をゲーム画面から取り除きます。パズルと必要な操作だけを残し、ロジックを変えずに視覚的なプレッシャーを減らします。",
    enableEyebrow: "Hue9を自分らしく",
    enableTitle: "数回のタップで機能を有効に。",
    enableIntro: "Hue9はiOSのアクセシビリティ設定に自動的に従います。シンボルモードとZenモードは、アプリ内でも直接選べます。",
    stepSymbolTitle: "Hue9のシンボルモード",
    stepSymbolBody: "Hue9 → 設定 → アクセシビリティ → シンボルモードを開きます。プレイ中の設定ボタンからも変更できます。",
    stepSystemTitle: "iOSのアクセシビリティ設定",
    stepSystemBody: "iOSの設定 → アクセシビリティを開き、VoiceOver、画面表示とテキストサイズ、動作、カラー以外で区別を設定します。",
    stepZenTitle: "Zenモード",
    stepZenBody: "Hue9 → 設定 → プレイスタイル → Zenモードを開きます。難易度を選び、画面上のタイマー、レベル、ヒントなしで遊べます。",
    commitmentEyebrow: "継続的な取り組み",
    commitmentTitle: "アクセシビリティに「完成」はありません。",
    commitmentBody: "Hue9はiPhoneとiPadでAppleのアクセシビリティ設定を使ってテストし、VoiceOverも実際に操作して確認しています。それ以上に大切なのが、実際の利用者からの声です。見えにくい、理解しにくい、操作しにくい点があれば、ぜひお知らせください。",
    commitmentNote: "対応状況は、デバイス、iOSのバージョン、言語、文字サイズによって異なる場合があります。",
    contactEyebrow: "次の改善にご協力ください",
    contactTitle: "アクセシビリティ上の障壁がありましたか？",
    contactBody: "発生した内容、使用しているデバイスとiOSのバージョン、有効だったアクセシビリティ設定をお知らせください。すべての報告がHue9の改善につながります。",
    contactButton: "アクセシビリティのフィードバックを送る",
    footerTagline: "純粋なロジックを、あなたらしい方法で。",
    privacy: "プライバシー",
    terms: "利用規約",
    support: "サポート"
  },
  "zh-Hans": {
    pageTitle: "Hue9 辅助功能 — 超越颜色的数独",
    pageDescription: "了解 Hue9: Color Sudoku 的辅助功能，包括符号模式、VoiceOver、更大字体、增强对比度、深色模式和减弱动态效果。",
    skip: "跳到内容",
    navLabel: "主导航",
    languageLabel: "语言",
    legalLabel: "法律链接",
    supportedLabel: "支持的辅助功能",
    navFeatures: "功能",
    navEnable: "如何启用",
    navContact: "联系",
    heroEyebrow: "Hue9 辅助功能",
    heroTitle: "超越颜色的数独。",
    heroIntro: "Hue9 的设计让颜色从来不是唯一的游戏方式。符号、语音情境、可缩放文字和更平缓的动态效果，让每一道谜题都清晰易读、易于理解，也更适合你。",
    explore: "探索功能",
    appStore: "在 App Store 中查看",
    pillVoiceOver: "VoiceOver",
    pillSymbols: "符号模式",
    pillText: "更大字体",
    pillMotion: "减弱动态效果",
    pillContrast: "增强对比度",
    heroCaptionSmall: "九种颜色。",
    heroCaptionLarge: "九个易于区分的符号。",
    principleEyebrow: "用第二种语言进行设计",
    principleTitle: "颜色创造谜题。<br>但无需独自承担所有信息。",
    principleBody: "辅助功能是 Hue9 游戏设计的一部分，并非事后添加。颜色传达的每一种状态都有另一种提示：形状、位置、对比度、文字或语音。",
    featuresEyebrow: "为不同的游戏方式而生",
    featuresTitle: "一块适应你的棋盘。",
    symbolsKicker: "不用颜色区分",
    symbolsTitle: "每种颜色都有第二种语言。",
    symbolsBody: "符号模式为 Hue9 的九种颜色分别搭配独特形状。在保留原有颜色的同时，棋盘、颜色选择器、候选笔记和视觉反馈都不再只依赖色调来传达信息。",
    symbolsSystem: "Hue9 还会自动响应 iOS 的“不用颜色区分”设置。",
    symbolScreenshotAlt: "真实的 Hue9 游戏棋盘，九种颜色分别搭配九个不同的符号。",
    symbolScreenshotLabel: "真实游戏棋盘",
    symbolScreenshotMode: "符号模式 · iPhone",
    voiceKicker: "VoiceOver",
    voiceTitle: "用语言描述整个棋盘。",
    voiceBody: "每个格子会先说明所在行和列，再朗读数值、候选笔记和当前状态。各项控制都有明确标签，重要的游戏结果也会在发生时播报。",
    voiceSampleLabel: "第 4 行，第 7 列",
    voiceSampleValue: "蓝色三角形，已选择",
    textKicker: "更大字体",
    textTitle: "灵活扩展，不会截断。",
    textBody: "Hue9 在整个 App 中支持动态字体。随着字体增大，导航、设置、新手引导和游戏信息会自动适应；空间有限时，布局也会重新排列。",
    motionKicker: "减弱动态效果",
    motionTitle: "更少动态，相同含义。",
    motionBody: "启用“减弱动态效果”后，入场移动、脉冲提示、晃动和庆祝效果会被移除或替换成短暂淡入淡出。反馈依然清晰，无需依赖移动。",
    contrastKicker: "对比度与外观",
    contrastTitle: "在任何光线下都舒适。",
    contrastBody: "浅色、深色和跟随系统外观适用于各项常用操作。“增强对比度”会强化重要边界和控制，精心选择的主题则让棋盘保持清晰易读。",
    zenKicker: "禅意模式",
    zenTitle: "一个更安静的思考空间。",
    zenBody: "禅意模式会从游戏画面中移除计时器、等级、提示和其他竞争信息，只保留谜题与必要控制，在不改变逻辑的前提下降低视觉压力。",
    enableEyebrow: "让 Hue9 更适合你",
    enableTitle: "轻点几下即可启用功能。",
    enableIntro: "Hue9 会自动跟随你的 iOS 辅助功能设置。符号模式和禅意模式也可直接在 App 内选择。",
    stepSymbolTitle: "Hue9 中的符号模式",
    stepSymbolBody: "打开 Hue9 → 设置 → 辅助功能 → 符号模式。游戏过程中也可通过设置按钮进行更改。",
    stepSystemTitle: "iOS 辅助功能设置",
    stepSystemBody: "打开 iOS 设置 → 辅助功能，以配置 VoiceOver、显示与文字大小、动态效果和不用颜色区分。",
    stepZenTitle: "禅意模式",
    stepZenBody: "打开 Hue9 → 设置 → 游戏风格 → 禅意模式。选择任意难度，即可在屏幕上不显示计时、等级或提示的情况下游戏。",
    commitmentEyebrow: "持续进行的工作",
    commitmentTitle: "辅助功能永远不会“完成”。",
    commitmentBody: "Hue9 会在 iPhone 和 iPad 上使用 Apple 的辅助功能设置进行测试，包括实际操作 VoiceOver 导航。真实使用反馈更为重要。如果有任何内容难以感知、理解或操作，请告诉我。",
    commitmentNote: "支持情况可能会因设备、iOS 版本、语言和文字大小而有所不同。",
    contactEyebrow: "帮助塑造下一步",
    contactTitle: "遇到辅助功能障碍？",
    contactBody: "请告诉我发生了什么、你使用的设备和 iOS 版本，以及当时启用了哪些辅助功能设置。每一份反馈都会帮助 Hue9 变得更好。",
    contactButton: "发送辅助功能反馈",
    footerTagline: "纯粹逻辑，用你的方式表达。",
    privacy: "隐私",
    terms: "条款",
    support: "支持"
  }
};

const languageSelect = document.getElementById("language-select");
const translatableElements = document.querySelectorAll("[data-i18n]");
const ariaElements = document.querySelectorAll("[data-i18n-aria]");
const altElements = document.querySelectorAll("[data-i18n-alt]");

function setLanguage(language) {
  const selected = normalizeLanguage(language);
  const strings = translations[selected];

  document.documentElement.lang = selected === "es" ? "es-ES" : selected;
  document.title = strings.pageTitle;
  document.querySelector('meta[name="description"]').content = strings.pageDescription;

  translatableElements.forEach((element) => {
    const key = element.dataset.i18n;
    if (strings[key]) {
      element.innerHTML = strings[key];
    }
  });

  ariaElements.forEach((element) => {
    const key = element.dataset.i18nAria;
    if (strings[key]) {
      element.setAttribute("aria-label", strings[key]);
    }
  });

  altElements.forEach((element) => {
    const key = element.dataset.i18nAlt;
    if (strings[key]) {
      element.setAttribute("alt", strings[key]);
    }
  });

  languageSelect.value = selected;

  try {
    localStorage.setItem("hue9-accessibility-language", selected);
  } catch {
    // The page remains fully usable when storage is unavailable.
  }
}

function normalizeLanguage(language) {
  const normalized = String(language || "").toLowerCase();
  if (normalized.startsWith("zh")) return "zh-Hans";
  if (normalized.startsWith("es")) return "es";
  if (normalized.startsWith("de")) return "de";
  if (normalized.startsWith("fr")) return "fr";
  if (normalized.startsWith("ja")) return "ja";
  return "en";
}

languageSelect.addEventListener("change", () => setLanguage(languageSelect.value));

const queryLanguage = new URLSearchParams(window.location.search).get("lang");
let storedLanguage = null;

try {
  storedLanguage = localStorage.getItem("hue9-accessibility-language");
} catch {
  storedLanguage = null;
}

const initialLanguage =
  queryLanguage ||
  storedLanguage ||
  navigator.language;

setLanguage(initialLanguage);
document.getElementById("year").textContent = new Date().getFullYear();
